version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      gomod:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"
    open-pull-requests-limit: 10
